-
  name: Inject SSH public key into remote system
  hosts: [remote]
  vars:
    remote_system_user: virtual
    host_user: hedeesa
  tasks:
    
    - name: Set authorized key taken from file
      authorized_key:
        user: '{{ remote_system_user }}'
        state: present
        key: "{{ lookup('file', '/home/{{ host_user }}/.ssh/id_rsa.pub') }}"
