- 
  name: change hostnamee
  hosts: [remote]
  become: true
  vars: 
    ansible_python_interpreter: /usr/bin/python3
  
  tasks:
  
    - name: change hostname to myserver
      hostname:
        name: '{{ansible_host}}'

    - name: add myself to /etc/hosts
      replace:
        dest: /etc/hosts
        regexp: '^127\.0\.0\.1[ \t]+localhost'
        replace: "127.0.0.1    localhost {{ansible_host}}"
        
